stages:
  - checkout
  - build
  - test
  - report

default:
  image: mcr.microsoft.com/playwright:v1.43.0-jammy

before_script:
  - npm ci

checkout:
  stage: checkout
  script:
    - echo "Repository cloned successfully."

build:
  stage: build
  script:
    - echo "No build step needed for this simple test project."

test:
  stage: test
  script:
    - npm run test
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 1 week

report:
  stage: report
  script:
    - echo "HTML test report is available in the artifacts."